/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i everylaunchermonitor_adaptor.h -l Server -a :everylaunchermonitor_adaptor.cpp com.gitee.wanywhn.EveryLauncherMonitor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "everylaunchermonitor_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class EveryLauncherMonitorAdaptor
 */

EveryLauncherMonitorAdaptor::EveryLauncherMonitorAdaptor(Server *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

EveryLauncherMonitorAdaptor::~EveryLauncherMonitorAdaptor()
{
    // destructor
}

void EveryLauncherMonitorAdaptor::myrun()
{
    // handle method call com.gitee.wanywhn.EveryLauncherMonitor.myrun
    parent()->myrun();
}

void EveryLauncherMonitorAdaptor::setFileMonitorInter(int sec)
{
    // handle method call com.gitee.wanywhn.EveryLauncherMonitor.setFileMonitorInter
    parent()->setFileMonitorInter(sec);
}

void EveryLauncherMonitorAdaptor::setWatchPaths(const QStringList &paths)
{
    // handle method call com.gitee.wanywhn.EveryLauncherMonitor.setWatchPaths
    parent()->setWatchPaths(paths);
}

