/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c EveryLauncherMonitorInterface -p everylaunchermonitor_interface.h: com.gitee.wanywhn.EveryLauncherMonitor.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef EVERYLAUNCHERMONITOR_INTERFACE_H
#define EVERYLAUNCHERMONITOR_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.gitee.wanywhn.EveryLauncherMonitor
 */
class EveryLauncherMonitorInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.gitee.wanywhn.EveryLauncherMonitor"; }

public:
    EveryLauncherMonitorInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~EveryLauncherMonitorInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> myrun()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("myrun"), argumentList);
    }

    inline QDBusPendingReply<> setFileMonitorInter(int sec)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(sec);
        return asyncCallWithArgumentList(QStringLiteral("setFileMonitorInter"), argumentList);
    }

    inline QDBusPendingReply<> setWatchPaths(const QStringList &paths)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(paths);
        return asyncCallWithArgumentList(QStringLiteral("setWatchPaths"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void fileWrited(const QStringList &files);
};

namespace com {
  namespace gitee {
    namespace wanywhn {
      typedef ::EveryLauncherMonitorInterface EveryLauncherMonitor;
    }
  }
}
#endif
