#!/bin/bash

action="$1"

if [ "$action" = configure ]; then
    set -e
    setcap cap_sys_admin+ep /usr/bin/everylauncher-monitor ||(echo "Failed set CAP_SYS_ADMIN on everylauncher-monitor" && false)
fi

#systemctl --global enable everylauncher-monitor.service
exit 0

