/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.gitee.wanywhn.everylauncherMonitor.xml -i server.h -a ServerAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "ServerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServerAdaptor
 */

ServerAdaptor::ServerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerAdaptor::~ServerAdaptor()
{
    // destructor
}

void ServerAdaptor::myrun()
{
    // handle method call local.Server.myrun
    QMetaObject::invokeMethod(parent(), "myrun");
}

void ServerAdaptor::setWatchPaths(const QStringList &paths)
{
    // handle method call local.Server.setWatchPaths
    QMetaObject::invokeMethod(parent(), "setWatchPaths", Q_ARG(QStringList, paths));
}

